import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { getCase, getCaseLogs, generateMasterReport } from '../api/axon';
import WalletInvestigation from './WalletInvestigation';
import ContractInvestigation from './ContractInvestigation';
import BulkInvestigation from './BulkInvestigation';
import { formatINR } from '../utils/indianFormat';

// ─── RISK BADGE ──────────────────────────────────────────────────────────────
function RiskPill({ score }) {
  const cfg =
    score >= 80 ? 'bg-red-500/15 text-red-400 border-red-500/30' :
    score >= 60 ? 'bg-orange-500/15 text-orange-400 border-orange-500/30' :
    score >= 40 ? 'bg-yellow-400/15 text-yellow-400 border-yellow-400/30' :
                  'bg-green-500/15 text-green-400 border-green-500/30';
  const label = score >= 80 ? 'CRITICAL' : score >= 60 ? 'HIGH' : score >= 40 ? 'MEDIUM' : 'LOW';
  return (
    <div className="flex items-center gap-1.5">
      <span className={`px-1.5 py-0.5 text-[9px] font-bold rounded border ${cfg}`}>{label}</span>
      <span className="text-xs font-mono text-gray-400">{score}</span>
    </div>
  );
}

// ─── MASTER REPORT MODAL ────────────────────────────────────────────────────
function MasterReportModal({ caseId, caseTitle, onClose }) {
  const [loading, setLoading]   = useState(true);
  const [report,  setReport]    = useState(null);
  const [error,   setError]     = useState(null);

  useEffect(() => {
    generateMasterReport(caseId)
      .then(setReport)
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, [caseId]);

  const handleDownload = () => {
    if (!report) return;
    const ai = report.ai_report || {};
    const content = `AXON INTELLIGENCE PLATFORM
CONFIDENTIAL FORENSIC REPORT
${'='.repeat(60)}

CASE: ${report.case_title}
CASE ID: #${report.case_id}
GENERATED: ${report.generated_at_str}
CLASSIFICATION: ${ai.report_classification || 'CONFIDENTIAL'}
CASE CLASSIFICATION: ${ai.case_classification || 'N/A'}

${'─'.repeat(60)}
EXECUTIVE SUMMARY
${'─'.repeat(60)}
${ai.executive_summary || 'N/A'}

${'─'.repeat(60)}
ENTITY STATISTICS
${'─'.repeat(60)}
Total Entities Scanned: ${report.stats?.total_entities || 0}
  Wallets:   ${report.stats?.wallets || 0}
  Contracts: ${report.stats?.contracts || 0}
Risk Distribution:
  CRITICAL:  ${report.stats?.critical || 0}
  HIGH:      ${report.stats?.high || 0}
  MEDIUM:    ${report.stats?.medium || 0}
  LOW:       ${report.stats?.low || 0}
Average Risk Score: ${report.stats?.average_risk || 0}/100

${'─'.repeat(60)}
ENTITY ROSTER
${'─'.repeat(60)}
${(report.entities || []).map((e, i) =>
  `${String(i+1).padStart(2, '0')}. ${e.address}  [${e.type.toUpperCase()}] [${e.class}]  Risk: ${e.risk_score}/100  Chain: ${e.chain}  Scanned: ${e.scanned_at}`
).join('\n')}

${'─'.repeat(60)}
KEY FINDINGS
${'─'.repeat(60)}
${(ai.key_findings || []).map((f, i) => `${i+1}. ${f}`).join('\n')}

${'─'.repeat(60)}
THREAT ASSESSMENT
${'─'.repeat(60)}
${ai.threat_assessment || 'N/A'}

${'─'.repeat(60)}
ENTITY BREAKDOWN
${'─'.repeat(60)}
${ai.entity_breakdown || 'N/A'}

${'─'.repeat(60)}
MONEY FLOW ANALYSIS
${'─'.repeat(60)}
${ai.money_flow_analysis || 'N/A'}

${'─'.repeat(60)}
LEGAL IMPLICATIONS
${'─'.repeat(60)}
${ai.legal_implications || 'N/A'}

${'─'.repeat(60)}
RECOMMENDED ACTIONS
${'─'.repeat(60)}
${(ai.recommended_actions || []).map((a, i) => `${i+1}. ${a}`).join('\n')}

${'─'.repeat(60)}
ANALYTICAL CONFIDENCE: ${ai.analytical_confidence || 0}%

${'='.repeat(60)}
END OF REPORT — AXON INTELLIGENCE PLATFORM v2.0
Generated by Axon AI (Groq / LLaMA-3.1)
This document is confidential. Unauthorized distribution prohibited.
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AXON-MASTER-REPORT-Case${caseId}-${new Date().toISOString().slice(0,10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center p-4 pt-8 bg-black/80 backdrop-blur-sm overflow-y-auto">
      <div className="w-full max-w-4xl bg-[#0a0f1a] border border-[#1e293b] rounded-2xl shadow-2xl">
        
        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-[#1e293b]">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="px-2 py-0.5 text-[10px] font-bold font-mono bg-red-600/30 text-red-400 rounded tracking-wider">CONFIDENTIAL</span>
              <span className="px-2 py-0.5 text-[10px] font-bold font-mono bg-blue-600/20 text-blue-400 rounded">FORENSIC DOSSIER</span>
            </div>
            <h2 className="text-2xl font-extrabold text-white">Master Case Report</h2>
            <p className="text-gray-500 text-sm mt-1">{caseTitle}</p>
          </div>
          <div className="flex items-center gap-2">
            {report && (
              <button
                onClick={handleDownload}
                className="px-4 py-2 text-sm font-bold bg-red-500/10 border border-red-500/30 text-red-400 hover:bg-red-500 hover:text-white rounded-lg transition-all"
              >
                ⬇ Download .txt
              </button>
            )}
            <button onClick={onClose} className="p-2 text-gray-500 hover:text-white transition-colors rounded-lg hover:bg-[#1e293b]">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {loading && (
            <div className="flex flex-col items-center py-16 gap-4">
              <div className="w-12 h-12 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
              <div className="text-sm text-gray-400 font-mono">Generating court-ready report via Groq AI…</div>
              <div className="text-xs text-gray-600">Analysing all case entities and building structured dossier</div>
            </div>
          )}

          {error && (
            <div className="p-4 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-sm">
              Failed to generate report: {error}
            </div>
          )}

          {report && !loading && (() => {
            const ai = report.ai_report || {};
            const clsCfg =
              ai.case_classification === 'CRITICAL' ? 'bg-red-500/15 text-red-400 border-red-500/30' :
              ai.case_classification === 'HIGH'     ? 'bg-orange-500/15 text-orange-400 border-orange-500/30' :
              ai.case_classification === 'MEDIUM'   ? 'bg-yellow-400/15 text-yellow-400 border-yellow-400/30' :
                                                      'bg-green-500/15 text-green-400 border-green-500/30';
            return (
              <>
                {/* Stat Bar */}
                <div className="grid grid-cols-4 gap-3">
                  {[
                    { label: 'Total Entities', value: report.stats?.total_entities, color: 'text-white' },
                    { label: 'Critical',        value: report.stats?.critical,       color: 'text-red-400' },
                    { label: 'High',            value: report.stats?.high,           color: 'text-orange-400' },
                    { label: 'Avg Risk',        value: `${report.stats?.average_risk}/100`, color: 'text-[#22d3ee]' },
                  ].map(s => (
                    <div key={s.label} className="bg-[#05080f] border border-[#1e293b] rounded-lg p-4 text-center">
                      <div className={`text-xl font-bold font-mono ${s.color}`}>{s.value}</div>
                      <div className="text-[10px] text-gray-500 uppercase tracking-wider mt-1">{s.label}</div>
                    </div>
                  ))}
                </div>

                {/* Case Classification */}
                <div className="flex items-center gap-3">
                  <span className="text-sm text-gray-500 font-mono">CASE CLASSIFICATION:</span>
                  <span className={`px-3 py-1 text-sm font-bold rounded border ${clsCfg}`}>{ai.case_classification || 'N/A'}</span>
                  <span className="text-sm text-gray-500 font-mono">CONFIDENCE: {ai.analytical_confidence || 0}%</span>
                </div>

                {/* Executive Summary */}
                <div className="bg-blue-500/5 border border-blue-500/20 rounded-xl p-5">
                  <div className="text-[10px] font-bold text-blue-400 uppercase tracking-widest mb-3">Executive Summary</div>
                  <p className="text-sm text-gray-200 leading-relaxed">{ai.executive_summary}</p>
                </div>

                {/* Key Findings */}
                {(ai.key_findings || []).length > 0 && (
                  <div>
                    <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-3">Key Findings</div>
                    <div className="space-y-2">
                      {ai.key_findings.map((f, i) => (
                        <div key={i} className="flex items-start gap-3 p-3 bg-[#05080f] border border-[#1e293b] rounded-lg">
                          <span className="text-[#22d3ee] text-xs font-mono shrink-0 mt-0.5">#{i+1}</span>
                          <span className="text-sm text-gray-300">{f}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* 3-col analysis */}
                <div className="grid md:grid-cols-3 gap-4">
                  {[
                    { title: 'Threat Assessment', text: ai.threat_assessment, color: 'border-red-500/20' },
                    { title: 'Money Flow Analysis', text: ai.money_flow_analysis, color: 'border-orange-500/20' },
                    { title: 'Legal Implications', text: ai.legal_implications, color: 'border-purple-500/20' },
                  ].map(s => (
                    <div key={s.title} className={`bg-[#05080f] border ${s.color} rounded-xl p-4`}>
                      <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-2">{s.title}</div>
                      <p className="text-xs text-gray-300 leading-relaxed">{s.text || '—'}</p>
                    </div>
                  ))}
                </div>

                {/* Recommended Actions */}
                {(ai.recommended_actions || []).length > 0 && (
                  <div>
                    <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-3">Recommended Actions</div>
                    <div className="space-y-2">
                      {ai.recommended_actions.map((a, i) => (
                        <div key={i} className="flex items-start gap-3 p-3 bg-green-500/5 border border-green-500/20 rounded-lg">
                          <span className="text-green-400 text-xs font-mono shrink-0 mt-0.5">▸</span>
                          <span className="text-sm text-gray-300">{a}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Entity Roster */}
                <div>
                  <div className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-3">
                    All Scanned Entities ({report.entities?.length || 0})
                  </div>
                  <div className="overflow-x-auto rounded-xl border border-[#1e293b]">
                    <table className="w-full text-xs font-mono">
                      <thead>
                        <tr className="border-b border-[#1e293b] bg-[#05080f]">
                          {['#', 'Address', 'Type', 'Class', 'Risk', 'Chain', 'Scanned'].map(h => (
                            <th key={h} className="py-3 px-4 text-[9px] text-gray-500 uppercase tracking-widest text-left">{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {(report.entities || []).map((e, i) => (
                          <tr key={i} className="border-b border-[#1e293b]/50 hover:bg-[#05080f] transition-colors">
                            <td className="py-2.5 px-4 text-gray-600">{i+1}</td>
                            <td className="py-2.5 px-4">
                              <span
                                className="text-[#22d3ee] hover:text-white cursor-pointer"
                                onClick={() => navigator.clipboard.writeText(e.address)}
                                title={e.address}
                              >
                                {e.address.slice(0,10)}…{e.address.slice(-6)}
                              </span>
                            </td>
                            <td className="py-2.5 px-4">
                              <span className={`px-1.5 py-0.5 text-[8px] font-bold rounded border ${
                                e.type === 'wallet' ? 'text-[#22d3ee] border-[#22d3ee]/30' : 'text-purple-400 border-purple-500/30'
                              }`}>{e.type.toUpperCase()}</span>
                            </td>
                            <td className="py-2.5 px-4 text-gray-400 max-w-[120px] truncate">{e.class}</td>
                            <td className="py-2.5 px-4"><RiskPill score={e.risk_score} /></td>
                            <td className="py-2.5 px-4 text-gray-500">{e.chain}</td>
                            <td className="py-2.5 px-4 text-gray-600">{e.scanned_at}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>

                <div className="text-center text-[10px] text-gray-600 font-mono pt-2">
                  AXON Intelligence Platform v2.0 · Generated by Groq AI (LLaMA-3.1-8B) · {report.generated_at_str}
                </div>
              </>
            );
          })()}
        </div>
      </div>
    </div>
  );
}

// ─── MAIN DASHBOARD ─────────────────────────────────────────────────────────
export default function CaseDashboard() {
  const { caseId } = useParams();
  const [caseData,       setCaseData]       = useState(null);
  const [caseLogs,       setCaseLogs]       = useState([]);
  const [loading,        setLoading]        = useState(true);
  const [activeTab,      setActiveTab]      = useState('overview');
  const [showReport,     setShowReport]     = useState(false);
  const [logsLoading,    setLogsLoading]    = useState(false);

  useEffect(() => {
    const fetchCase = async () => {
      try {
        const data = await getCase(caseId);
        setCaseData(data);
      } catch (err) {
        console.error("Failed to load case data:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchCase();
  }, [caseId]);

  // Load all case logs for the overview
  useEffect(() => {
    if (!caseId) return;
    setLogsLoading(true);
    getCaseLogs(caseId)
      .then(setCaseLogs)
      .catch(err => console.error("Failed to load case logs:", err))
      .finally(() => setLogsLoading(false));
  }, [caseId]);

  if (loading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center h-full animate-pulse">
        <div className="w-16 h-16 border-4 border-[#22d3ee] border-t-transparent rounded-full animate-spin mb-4" />
        <div className="text-[#22d3ee] font-mono tracking-widest">LOADING CASE WORKSPACE...</div>
      </div>
    );
  }

  if (!caseData) {
    return (
      <div className="p-8 text-center text-red-400">
        <h2 className="text-2xl font-bold">Case Not Found</h2>
        <Link to="/cases" className="text-[#22d3ee] hover:underline mt-4 inline-block">Return to Cases</Link>
      </div>
    );
  }

  const tabs = [
    { id: 'overview', label: 'Case Overview', icon: '📋' },
    { id: 'wallet',   label: 'Wallet Scan',   icon: '🔍' },
    { id: 'contract', label: 'Contract Scan', icon: '📜' },
    { id: 'bulk',     label: 'Bulk Scanner',  icon: '⚡' },
  ];

  // Compute stats from caseLogs
  const totalEntities = caseLogs.length;
  const criticalCount = caseLogs.filter(e => e.risk_score >= 80).length;
  const highCount     = caseLogs.filter(e => e.risk_score >= 60 && e.risk_score < 80).length;
  const walletCount   = caseLogs.filter(e => e.entity_type === 'wallet').length;
  const contractCount = caseLogs.filter(e => e.entity_type === 'contract').length;

  return (
    <div className="max-w-7xl mx-auto space-y-6 animate-fade-in pb-20">
      
      {/* HEADER */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end border-b border-[#1e293b] pb-6 gap-6">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <Link to="/cases" className="text-gray-500 hover:text-white transition-colors text-sm">
              ← Back to Cases
            </Link>
            <span className="px-3 py-1 text-[10px] font-mono font-bold tracking-widest text-purple-400 bg-purple-500/10 border border-purple-500/30 rounded-full">
              CASE #{caseData.id}
            </span>
            <span className={`px-2 py-0.5 text-[9px] font-bold rounded border ${
              caseData.status === 'Open'
                ? 'bg-green-500/20 text-green-400 border-green-500/40'
                : 'bg-gray-500/20 text-gray-400 border-gray-500/40'
            }`}>
              {caseData.status.toUpperCase()}
            </span>
          </div>
          <h1 className="text-3xl font-extrabold text-white tracking-tight">{caseData.title}</h1>
          {caseData.description && (
            <p className="text-gray-500 mt-2 text-sm max-w-2xl">{caseData.description}</p>
          )}
        </div>
        
        <div className="flex items-center gap-2 flex-wrap">
          {activeTab === 'overview' && caseLogs.length > 0 && (
            <button
              onClick={() => setShowReport(true)}
              className="px-4 py-2 text-sm font-bold bg-gradient-to-r from-blue-600/20 to-purple-600/20 border border-blue-500/40 text-blue-400 hover:from-blue-600 hover:to-purple-600 hover:text-white rounded-lg transition-all flex items-center gap-2"
            >
              <span>⚖️</span> Generate Master Report
            </button>
          )}
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-4 py-2 text-sm font-bold rounded transition-all flex items-center gap-2 ${
                activeTab === tab.id
                  ? 'bg-[#22d3ee] text-[#05080f] shadow-[0_0_15px_rgba(34,211,238,0.4)]'
                  : 'bg-[#0a0f1a] text-gray-500 border border-[#1e293b] hover:text-white hover:border-[#22d3ee]/50'
              }`}
            >
              <span>{tab.icon}</span>
              {tab.label}
            </button>
          ))}
        </div>
      </div>

      {/* CONTENT */}
      <div className="pt-2">
        {activeTab === 'overview' && (
          <div className="space-y-8">
            
            {/* Stats Row */}
            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
              {[
                { label: 'Total Entities',  value: totalEntities,   color: 'text-white' },
                { label: 'Wallets',         value: walletCount,     color: 'text-[#22d3ee]' },
                { label: 'Contracts',       value: contractCount,   color: 'text-purple-400' },
                { label: 'Critical Threats',value: criticalCount,   color: 'text-red-400' },
                { label: 'High Risk',       value: highCount,       color: 'text-orange-400' },
              ].map(s => (
                <div key={s.label} className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl p-4 text-center">
                  <div className={`text-2xl font-bold font-mono ${s.color}`}>{s.value}</div>
                  <div className="text-[10px] text-gray-500 uppercase tracking-wider mt-1">{s.label}</div>
                </div>
              ))}
            </div>

            {/* All Scanned Entities Table */}
            <div className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl overflow-hidden">
              <div className="flex items-center justify-between px-6 py-4 border-b border-[#1e293b]">
                <div>
                  <h3 className="text-sm font-bold text-white flex items-center gap-2">
                    <span className="w-1.5 h-5 rounded-full bg-[#22d3ee]" />
                    All Scanned Entities
                  </h3>
                  <p className="text-xs text-gray-500 mt-0.5">All addresses analyzed in this case, sorted by risk</p>
                </div>
                <span className="text-xs font-mono text-gray-500">{caseLogs.length} records</span>
              </div>

              {logsLoading ? (
                <div className="flex justify-center py-12">
                  <div className="w-8 h-8 border-2 border-[#22d3ee] border-t-transparent rounded-full animate-spin" />
                </div>
              ) : caseLogs.length === 0 ? (
                <div className="py-12 text-center text-gray-600 text-sm">
                  No entities scanned yet. Use the scanner tabs to begin your investigation.
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-sm font-mono">
                    <thead>
                      <tr className="border-b border-[#1e293b] bg-[#05080f]">
                        {['Address', 'Type', 'Class', 'Risk Score', 'Chain', 'Scan Depth', 'Scanned At', 'Top Signal'].map(h => (
                          <th key={h} className="py-3 px-5 text-[9px] font-bold text-gray-500 uppercase tracking-widest text-left whitespace-nowrap">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody>
                      {[...caseLogs]
                        .sort((a, b) => b.risk_score - a.risk_score)
                        .map(log => {
                          const topSignal = (log.triggered_signals || [])[0];
                          return (
                            <tr key={log.id} className="border-b border-[#1e293b]/50 hover:bg-[#05080f] transition-colors">
                              <td className="py-3 px-5">
                                <span
                                  className="text-[#22d3ee] hover:text-white cursor-pointer"
                                  onClick={() => navigator.clipboard.writeText(log.entity_address)}
                                  title={log.entity_address}
                                >
                                  {log.entity_address.slice(0, 10)}…{log.entity_address.slice(-6)}
                                </span>
                              </td>
                              <td className="py-3 px-5">
                                <span className={`px-1.5 py-0.5 text-[9px] font-bold rounded border ${
                                  log.entity_type === 'wallet'
                                    ? 'text-[#22d3ee] border-[#22d3ee]/30 bg-[#22d3ee]/5'
                                    : 'text-purple-400 border-purple-500/30 bg-purple-500/5'
                                }`}>{(log.entity_type || 'wallet').toUpperCase()}</span>
                              </td>
                              <td className="py-3 px-5 text-gray-400 text-xs max-w-[130px] truncate">{log.entity_class || 'Unknown'}</td>
                              <td className="py-3 px-5"><RiskPill score={log.risk_score} /></td>
                              <td className="py-3 px-5 text-gray-500 text-xs">{log.chain || 'ETH'}</td>
                              <td className="py-3 px-5">
                                <span className="px-1.5 py-0.5 text-[9px] bg-[#1e293b] text-gray-400 rounded uppercase">{log.scan_depth || 'quick'}</span>
                              </td>
                              <td className="py-3 px-5 text-gray-600 text-xs">
                                {new Date(log.scan_timestamp * 1000).toLocaleString('en-IN', {
                                  day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', hour12: true
                                })}
                              </td>
                              <td className="py-3 px-5 text-gray-500 text-xs max-w-[200px] truncate">
                                {topSignal
                                  ? <span className="flex items-center gap-1"><span>{topSignal.icon || '🔸'}</span><span>{(topSignal.reason || '').slice(0, 50)}{(topSignal.reason || '').length > 50 ? '…' : ''}</span></span>
                                  : <span className="text-gray-700">—</span>
                                }
                              </td>
                            </tr>
                          );
                        })}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Case Meta */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl p-6">
                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Case Details</h3>
                {[
                  { label: 'Case ID',       value: `#${caseData.id}` },
                  { label: 'Status',        value: caseData.status },
                  { label: 'Created',       value: new Date(caseData.created_at * 1000).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }) },
                  { label: 'Total Entities',value: totalEntities },
                  { label: 'Critical',      value: criticalCount },
                ].map(item => (
                  <div key={item.label} className="flex justify-between items-center py-2.5 border-b border-[#1e293b]/50">
                    <span className="text-sm text-gray-500">{item.label}</span>
                    <span className="text-sm font-bold font-mono text-white">{item.value}</span>
                  </div>
                ))}
              </div>

              {/* Notes */}
              <div className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl p-6">
                <h3 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4">Case Notes</h3>
                {caseData.notes && caseData.notes.length > 0 ? (
                  <div className="space-y-3 max-h-64 overflow-y-auto">
                    {caseData.notes.map(note => (
                      <div key={note.id} className="p-3 bg-[#05080f] border border-[#1e293b] rounded-lg">
                        <p className="text-sm text-gray-300">{note.content}</p>
                        <p className="text-[10px] text-gray-600 mt-1.5 font-mono">
                          {new Date(note.created_at * 1000).toLocaleString('en-IN')}
                        </p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-gray-600">No notes added yet.</p>
                )}
              </div>
            </div>
          </div>
        )}

        {activeTab === 'wallet' && (
          <div className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl p-6 shadow-2xl">
            <WalletInvestigation caseId={parseInt(caseId)} />
          </div>
        )}
        
        {activeTab === 'contract' && (
          <div className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl p-6 shadow-2xl">
            <ContractInvestigation caseId={parseInt(caseId)} />
          </div>
        )}

        {activeTab === 'bulk' && (
          <div className="bg-[#0a0f1a] border border-[#1e293b] rounded-xl p-6 shadow-2xl">
            <BulkInvestigation caseId={parseInt(caseId)} />
          </div>
        )}
      </div>

      {/* Master Report Modal */}
      {showReport && (
        <MasterReportModal
          caseId={parseInt(caseId)}
          caseTitle={caseData.title}
          onClose={() => setShowReport(false)}
        />
      )}
    </div>
  );
}
