import io
import time
from sqlalchemy.orm import Session
from database.models import VerificationReport, InvestigationLog
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from modules.cross_chain import detect_address_type


# ─── FORENSIC REPORT CONSTANTS ───────────────────────────────────────────────
ENGINE_VERSION = "AXON Behavioral Forensic Engine v2.0"
METHODOLOGY_DISCLAIMER = (
    "This report was generated by the AXON Behavioral Forensic Engine v2.0. "
    "Risk scores are computed algorithmically using deterministic heuristics "
    "and should be corroborated with independent forensic analysis. Sections "
    "labeled 'AI-Assisted' contain machine-generated interpretations that are "
    "non-evidentiary and do not constitute expert testimony."
)

def _risk_label(score: int) -> str:
    """Map a 0-100 score to the canonical 5-tier risk classification."""
    if score >= 80: return "CRITICAL"
    if score >= 60: return "HIGH"
    if score >= 40: return "MEDIUM"
    if score >= 20: return "LOW"
    return "MINIMAL"

def _page_footer(canvas, doc):
    """Draw page number footer on every page."""
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(
        letter[0] - 0.5 * inch, 0.4 * inch,
        f"Page {canvas.getPageNumber()} — {ENGINE_VERSION} — CONFIDENTIAL"
    )
    canvas.drawString(
        0.5 * inch, 0.4 * inch,
        "AXON Verifiable Investigation Report"
    )
    canvas.restoreState()


ENGINE_TO_FORENSIC = {
    "risk score lowered to MODERATE": "Risk assessment adjusted. Observed behavior is consistent with known exchange activity. Entity classification applied.",
    "risk score lowered to LOW": "Risk assessment reflects confirmed entity classification. Behavioral signals are expected for this entity type.",
    "Trusted protocol suppression applied": "Risk assessment reflects known protocol classification. Administrative controls observed are consistent with regulatory compliance design, not exploitation.",
    "auto-detected: poly network exploiter": "Threat corpus match: Poly Network Exploiter",
    "risk score should be lowered": "Risk assessment adjusted based on classification",
}

def translate(text: str) -> str:
    if not text or not isinstance(text, str): return str(text)
    for k, v in ENGINE_TO_FORENSIC.items():
        if k in text:
            text = text.replace(k, v)
    return text

def _is_valid(data):
    if not data: return False
    if isinstance(data, str):
        d = data.lower().strip()
        if d in ["data not available", "unknown", "n/a", "null", "none", "0 eth", "[]", "{}"]: return False
    return True

def _build_table(headers, data_rows, col_widths=None):
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    styles = getSampleStyleSheet()
    cell_style = ParagraphStyle('CellStyle', parent=styles['Normal'], fontSize=9, textColor=colors.lightgrey, wordWrap='CJK')
    header_style = ParagraphStyle('HeaderStyle', parent=styles['Normal'], fontSize=9, textColor=colors.whitesmoke, fontName='Helvetica-Bold')

    formatted_headers = [Paragraph(str(h), header_style) for h in headers]
    formatted_data = []
    for row in data_rows:
        formatted_row = []
        for cell in row:
            if isinstance(cell, str):
                formatted_row.append(Paragraph(cell, cell_style))
            else:
                formatted_row.append(cell)
        formatted_data.append(formatted_row)
        
    table_data = [formatted_headers] + formatted_data
    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2a2d3e")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#1e1e24")),
        ('TEXTCOLOR', (0,1), (-1,-1), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
    ]))
    return t

def generate_pdf_report(report_id: str, db: Session) -> bytes:
    report = db.query(VerificationReport).filter(VerificationReport.report_id == report_id).first()
    if not report:
        raise ValueError(f"Report {report_id} not found in database.")

    inv_log = None
    if report.entity_type == "bulk_batch":
        inv_log = db.query(InvestigationLog).filter(
            InvestigationLog.entity_address == report.entity_address,
            InvestigationLog.entity_type == "bulk_batch"
        ).first()
    else:
        inv_log = db.query(InvestigationLog).filter(
            InvestigationLog.entity_address == report.entity_address,
            InvestigationLog.entity_type == report.entity_type,
            InvestigationLog.scan_depth == report.scan_depth
        ).order_by(InvestigationLog.scan_timestamp.desc()).first()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    Story = []

    # COVER BLOCK
    Story.append(Paragraph("<b>AXON - Verifiable Investigation Report</b>", styles["Title"]))
    Story.append(Spacer(1, 12))
    
    timestamp_str = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(report.scan_timestamp))
    risk_label = _risk_label(int(report.risk_score))
    Story.append(Paragraph(f"<b>Report ID:</b> {report.report_id}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Target Entity:</b> {report.entity_address}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Timestamp:</b> {timestamp_str}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Scan Depth:</b> {report.scan_depth.upper()}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Classification Badge:</b> [{report.entity_type.upper()}]", styles["Normal"]))
    Story.append(Paragraph(f"<b>Risk Band:</b> {report.risk_score}/100 — {risk_label}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Engine:</b> {ENGINE_VERSION}", styles["Normal"]))
    
    if inv_log and isinstance(inv_log.raw_data, dict):
        meta = inv_log.raw_data.get("report_metadata", {})
        examiner = meta.get("examiner_name", "AXON Automated Engine")
        agency = meta.get("agency", "")
        case_ref = meta.get("case_reference", "")
        Story.append(Spacer(1, 6))
        Story.append(Paragraph(f"<b>Examiner:</b> {examiner}", styles["Normal"]))
        if agency:
            Story.append(Paragraph(f"<b>Agency:</b> {agency}", styles["Normal"]))
        if case_ref:
            Story.append(Paragraph(f"<b>Case Reference:</b> {case_ref}", styles["Normal"]))

    Story.append(Spacer(1, 8))
    
    # METHODOLOGY DISCLAIMER
    disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=7, textColor=colors.grey, italic=True)
    Story.append(Paragraph(METHODOLOGY_DISCLAIMER, disclaimer_style))
    Story.append(Spacer(1, 16))

    if inv_log and isinstance(inv_log.raw_data, dict):
        raw = inv_log.raw_data

        # PRE-FLIGHT QUALITY GATES
        if report.entity_type == "wallet":
            identity = raw.get("identity", {})
            if not identity or identity.get("txCount") is None:
                Story.append(Paragraph("<b>[DATA NORMALIZATION ERROR]</b> Raw data received, but mapping was incomplete. Report generation aborted.", styles["Heading2"]))
                doc.build(Story, onFirstPage=_page_footer, onLaterPages=_page_footer)
                return buffer.getvalue()
            
        if report.entity_type == "contract":
            info = raw.get("info", {})
            if "verified" not in info:
                Story.append(Paragraph("<b>[DATA NORMALIZATION ERROR]</b> Contract verification status missing. Report generation aborted.", styles["Heading2"]))
                doc.build(Story, onFirstPage=_page_footer, onLaterPages=_page_footer)
                return buffer.getvalue()

        if report.entity_type == "wallet":
            identity = raw.get("identity", {})
            risk = raw.get("risk", {})
            osint = raw.get("osint", {})
            mixer = raw.get("mixer", {})
            exchange = raw.get("exchange", {})
            txs = raw.get("transactions", [])
            graph = raw.get("graph", {})
            ai = risk.get("analyticalSynthesis", {}) or risk.get("aiAnalysis", {})

            # SECTION 1 - EVIDENCE INTEGRITY
            Story.append(Paragraph("<b>SECTION 1 - EVIDENCE INTEGRITY</b>", styles["Heading2"]))
            Story.append(Paragraph(f"<b>SHA-256 Hash:</b> {report.report_hash}", styles["Normal"]))
            Story.append(Paragraph("<b>Signed:</b> Engine v2.0 | Node Source: Primary Intel Node", styles["Normal"]))
            Story.append(Paragraph("<i>Integrity verification failed. The calculated SHA-256 hash differs from the embedded report hash. Possible causes include: File modification, Export conversion, File corruption. Manual verification recommended.</i>", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 2 - EXECUTIVE SUMMARY
            Story.append(Paragraph("<b>EXECUTIVE SUMMARY</b>", styles["Heading1"]))
            tx_count = identity.get("tx_count") or len(txs)
            
            if ai and _is_valid(ai.get("verdict")):
                verdict = ai.get("verdict")
                Story.append(Paragraph(f"Target is a <b>{identity.get('wallet_type', 'EOA')}</b> exhibiting {tx_count} transactions. <b>{verdict}</b>", styles["Normal"]))
                if _is_valid(ai.get("hypothesis")):
                    Story.append(Paragraph(f"<b>Assessment:</b> {translate(ai.get('hypothesis'))}", styles["Normal"]))
            else:
                Story.append(Paragraph(f"Target is a <b>{identity.get('wallet_type', 'EOA')}</b> exhibiting {tx_count} transactions. Algorithmic Risk Profile: <b>{translate(risk.get('label', 'LOW'))}</b>.", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # KEY FINDINGS
            Story.append(Paragraph("<b>KEY FINDINGS</b>", styles["Heading2"]))
            findings = []
            if osint and _is_valid(osint.get("corpus_match")):
                findings.append(f"Threat corpus match: {osint.get('corpus_match')} (Source: OSINT Database, Confidence: High, Method: Exact Address Match)")
            findings.append(f"{tx_count} observed transactions (Source: On-Chain Data, Confidence: Verified, Method: RPC Node)")
            if _is_valid(risk.get("factors")):
                for factor in risk.get("factors", [])[:3]:
                    findings.append(translate(factor.get('reason')) + " (Source: Axon Engine, Confidence: High, Method: Behavioral Heuristics)")
            for f in findings:
                Story.append(Paragraph(f"• {f}", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 3 - SUBJECT PROFILE
            Story.append(Paragraph("<b>SUBJECT PROFILE</b>", styles["Heading2"]))
            addr_info = detect_address_type(report.entity_address)
            Story.append(Paragraph(f"<b>Network/Coin:</b> {addr_info.get('coin', 'Unknown')}", styles["Normal"]))
            explorer = addr_info.get("explorer", "N/A")
            if _is_valid(explorer):
                Story.append(Paragraph(f"<b>Explorer Link:</b> <a href='{explorer}'>{explorer}</a>", styles["Normal"]))
            
            # Coin Identifier Tier 1 Data
            address_intel = identity.get("address_intelligence")
            if address_intel:
                Story.append(Spacer(1, 6))
                Story.append(Paragraph("<b>Coin Identifier (Tier 1 Intelligence)</b>", styles["Heading3"]))
                Story.append(Paragraph(f"<b>Blockchain Family:</b> {address_intel.get('family', 'N/A')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Address Type:</b> {address_intel.get('address_type', 'N/A')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Encoding:</b> {address_intel.get('encoding', 'N/A')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Checksum Validation:</b> {address_intel.get('checksum', 'N/A')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Length:</b> {address_intel.get('length', 'N/A')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Prefix:</b> {address_intel.get('prefix', 'N/A')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Detection Method:</b> {address_intel.get('identification_method', 'N/A')}", styles["Normal"]))
                supported_str = 'Supported' if address_intel.get('supported') else 'Unsupported'
                Story.append(Paragraph(f"<b>Supported Status:</b> {supported_str}", styles["Normal"]))
                comp_chains = ", ".join(address_intel.get('possible_networks', []))
                Story.append(Paragraph(f"<b>Compatible Chains:</b> {comp_chains or 'N/A'}", styles["Normal"]))
                Story.append(Spacer(1, 6))

            if _is_valid(identity.get("first_tx_date")):
                Story.append(Paragraph(f"<b>First Activity:</b> {identity.get('first_tx_date')}", styles["Normal"]))
            if _is_valid(identity.get("last_tx_date")):
                Story.append(Paragraph(f"<b>Last Activity:</b> {identity.get('last_tx_date')}", styles["Normal"]))
            if _is_valid(identity.get("balance_wei")):
                Story.append(Paragraph(f"<b>Native Balance (Wei):</b> {identity.get('balance_wei')}", styles["Normal"]))
            if _is_valid(identity.get("walletAgeDays")):
                Story.append(Paragraph(f"<b>Wallet Age:</b> {identity.get('walletAgeDays')}", styles["Normal"]))
            if _is_valid(identity.get("walletType")):
                Story.append(Paragraph(f"<b>Wallet Type:</b> {identity.get('walletType')}", styles["Normal"]))
            if _is_valid(identity.get("ens")):
                Story.append(Paragraph(f"<b>ENS / Domain:</b> {identity.get('ens')}", styles["Normal"]))
            class_label = identity.get("entityClass") or identity.get("protocolCategory")
            if _is_valid(class_label):
                Story.append(Paragraph(f"<b>Entity Classification:</b> {class_label} (Source: Threat Corpus)", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # THREAT DB
            Story.append(Paragraph("<b>THREAT INTELLIGENCE</b>", styles["Heading2"]))
            if _is_valid(risk.get("factors")):
                rows = []
                for factor in risk.get("factors", []):
                    rows.append(["Axon Engine", "Behavioral", "High", translate(factor.get('reason')), "Chain Analysis"])
                if rows:
                    Story.append(_build_table(["Threat Source", "Threat Category", "Confidence", "Evidence", "Reference"], rows, [80, 80, 60, 150, 60]))
                Story.append(Spacer(1, 12))
            else:
                Story.append(Paragraph("Not available on this blockchain", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # EVIDENCE: TIMELINE
            Story.append(Paragraph("<b>TIMELINE RECONSTRUCTION</b>", styles["Heading2"]))
            if txs:
                tx_limit = 50 if report.scan_depth == "deep" else 15
                Story.append(Paragraph(f"<b>EVIDENCE:</b> (Showing {min(len(txs), tx_limit)} of {len(txs)} transactions)", styles["Normal"]))
                
                defi_interactions = graph.get("defi_interactions", []) if isinstance(graph, dict) else []
                defi_map = {d.get("hash"): d.get("simple_name") for d in defi_interactions if d.get("hash")}
                
                rows = []
                for tx in txs[:tx_limit]:
                    ts = tx.get("timeStamp")
                    try: dstr = time.strftime("%Y-%m-%d %H:%M", time.gmtime(int(ts)))
                    except: dstr = "N/A"
                    
                    tx_hash = tx.get("hash", "")
                    op_name = defi_map.get(tx_hash)
                    
                    try:
                        val_num = int(tx.get('value', 0))
                        if op_name:
                            val = op_name.capitalize()
                        elif tx.get('token_symbol'):
                            val = f"{tx.get('token_value_formatted')} {tx.get('token_symbol')}"
                        elif val_num == 0 and tx.get('input') not in ['', '0x']:
                            val = "Token Transfer"
                        else:
                            val = f"{(val_num / 10**18):.5f} {identity.get('nativeSymbol', 'ETH')}"
                    except: val = f"0 {identity.get('nativeSymbol', 'ETH')}"
                    is_in = tx.get("to", "").lower() == report.entity_address.lower()
                    rows.append([dstr, tx_hash[:8]+"...", "IN" if is_in else "OUT", val])
                if rows:
                    Story.append(_build_table(["Date", "Hash", "Dir", "Value / Operation"], rows, [100, 80, 40, 100]))
                Story.append(Spacer(1, 12))
            else:
                Story.append(Paragraph("Not available on this blockchain", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # COUNTERPARTIES
            Story.append(Paragraph("<b>COUNTERPARTIES</b>", styles["Heading2"]))
            if graph and _is_valid(graph.get("nodes")) and len(graph.get("nodes", [])) > 0:
                nodes = graph.get("nodes", [])
                rows = []
                for n in nodes[:10]:
                    ctype = n.get("type", "Unknown")
                    if ctype == "default": ctype = "Unclassified"
                    tx_c = str(n.get("interaction_count", n.get("tx_count", "N/A")))
                    rows.append([n.get("id", "")[:12]+"...", ctype, tx_c, str(n.get("total_value", "N/A")), str(n.get("last_seen", "N/A")), str(n.get("risk", 0))])
                if rows:
                    Story.append(_build_table(["Address", "Known Entity", "Tx Count", "Total Val", "Last Seen", "Threat Lvl"], rows, [80, 70, 50, 50, 60, 50]))
                Story.append(Spacer(1, 12))
            else:
                Story.append(Paragraph("Not available on this blockchain", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # ASSET INVENTORY
            Story.append(Paragraph("<b>ASSET INVENTORY</b>", styles["Heading2"]))
            if _is_valid(raw.get("holdings")):
                holdings = raw.get("holdings", {})
                rows = []
                if isinstance(holdings, list):
                    for h in holdings:
                        if isinstance(h, dict):
                            rows.append([h.get("chain", ""), "N/A", "N/A", "N/A", "N/A"])
                elif isinstance(holdings, dict):
                    count = holdings.get("erc20_count", 0)
                    count_str = "Not collected at QUICK depth" if str(count) == "0" else str(count)
                    rows.append(["ERC-20 Tokens", count_str, "N/A", "N/A", "N/A"])
                if rows:
                    Story.append(_build_table(["Assets", "Stablecoins", "NFTs", "Contracts", "Protocols"], rows, [80, 70, 50, 60, 60]))
                Story.append(Spacer(1, 12))
            else:
                Story.append(Paragraph("<i>No asset inventory data collected at this depth or chain.</i>", styles["Normal"]))
                Story.append(Spacer(1, 12))
            
            # EXCHANGE & KYC
            Story.append(Paragraph("<b>FINANCIAL SUMMARY (EXCHANGE & KYC)</b>", styles["Heading2"]))
            if exchange and _is_valid(exchange.get("detected")) and exchange.get("detected"):
                Story.append(Paragraph(f"<b>Exchange Activity Detected:</b> {exchange.get('summary', '')}", styles["Normal"]))
                Story.append(Paragraph("<b>Recommended legal mechanism:</b> Subpoena / MLAT to exchange compliance.", styles["Normal"]))
                Story.append(Spacer(1, 12))
            else:
                Story.append(Paragraph("<i>No centralized exchange interactions detected.</i>", styles["Normal"]))
                Story.append(Spacer(1, 12))
                
            # PROTOCOL ACTIVITY / MIXER
            Story.append(Paragraph("<b>PROTOCOL ACTIVITY (MIXERS & BRIDGES)</b>", styles["Heading2"]))
            if mixer and _is_valid(mixer.get("findings")) and len(mixer.get("findings")) > 0:
                Story.append(Paragraph(f"<b>Mixers Detected:</b> {len(mixer.get('findings'))}", styles["Normal"]))
                Story.append(Spacer(1, 12))
            else:
                Story.append(Paragraph("<i>No mixer or bridge interactions detected.</i>", styles["Normal"]))
                Story.append(Spacer(1, 12))
            
            # AI-ASSISTED INTERPRETATION (NON-EVIDENTIARY)
            if ai and _is_valid(ai.get("prosecution_summary")):
                Story.append(Paragraph("<b>AI-ASSISTED INTERPRETATION (NON-EVIDENTIARY)</b>", styles["Heading2"]))
                ai_disclaimer = ParagraphStyle('AIDisclaimer', parent=styles['Normal'], fontSize=7, textColor=colors.grey, italic=True)
                Story.append(Paragraph("The following analysis was generated by a Large Language Model (LLM) and does not constitute expert testimony. It is provided as an investigative aid only.", ai_disclaimer))
                Story.append(Spacer(1, 6))
                Story.append(Paragraph(f"<b>Prosecution Hypothesis:</b> {ai.get('prosecution_summary')}", styles["Normal"]))
                Story.append(Paragraph(f"<b>Defense Hypothesis:</b> {ai.get('defense_summary')}", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # APPENDIX: METHODOLOGY
            Story.append(PageBreak())
            Story.append(Paragraph("<b>APPENDIX A: METHODOLOGY & RISK SCORE</b>", styles["Heading1"]))
            Story.append(Spacer(1, 12))
            Story.append(Paragraph(f"<b>Overall Calculated Risk Score:</b> {report.risk_score} / 100", styles["Normal"]))
            Story.append(Spacer(1, 12))
            if _is_valid(risk.get("factors")):
                Story.append(Paragraph("<b>Scoring Breakdown:</b>", styles["Normal"]))
                for factor in risk.get("factors", []):
                    Story.append(Paragraph(f"- {translate(factor.get('reason'))} ", styles["Normal"]))
            Story.append(Spacer(1, 12))

        elif report.entity_type == "contract":
            info = raw.get("info", {})
            risk = raw.get("risk", {})
            slither = raw.get("slither", [])
            goplus = raw.get("goplus", {})
            abi = raw.get("abi", [])
            
            # SECTION 1 - EVIDENCE INTEGRITY
            Story.append(Paragraph("<b>SECTION 1 - EVIDENCE INTEGRITY</b>", styles["Heading2"]))
            Story.append(Paragraph(f"<b>SHA-256 Hash:</b> {report.report_hash}", styles["Normal"]))
            Story.append(Paragraph("<b>Signed:</b> Engine v2.0 | Node Source: Primary Intel Node", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 2 - EXECUTIVE SUMMARY
            Story.append(Paragraph("<b>SECTION 2 - EXECUTIVE SUMMARY</b>", styles["Heading2"]))
            Story.append(Paragraph(f"Target is a Smart Contract with a {translate(risk.get('label', 'LOW'))} risk profile (Score: {report.risk_score}).", styles["Normal"]))
            if _is_valid(risk.get("overall")):
                Story.append(Paragraph(f"<b>Verdict:</b> {risk.get('overall')}", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 3 - CONTRACT PROFILE
            Story.append(Paragraph("<b>SECTION 3 - CONTRACT PROFILE</b>", styles["Heading2"]))
            addr_info = detect_address_type(report.entity_address)
            explorer = addr_info.get("explorer", "")
            if _is_valid(explorer):
                Story.append(Paragraph(f"<b>Explorer Link:</b> <a href='{explorer}'>{explorer}</a>", styles["Normal"]))
            if _is_valid(info.get('tokenName')):
                Story.append(Paragraph(f"<b>Token Name / Metadata:</b> {info.get('tokenName')}", styles["Normal"]))
            if _is_valid(info.get('compiler')):
                Story.append(Paragraph(f"<b>Compiler:</b> {info.get('compiler')}", styles["Normal"]))
            Story.append(Paragraph(f"<b>Source Code Verified:</b> {'Yes' if info.get('verified') else 'No'}", styles["Normal"]))
            if 'is_proxy' in info:
                Story.append(Paragraph(f"<b>Proxy Contract:</b> {'Yes' if info.get('is_proxy') else 'No'}", styles["Normal"]))
            if _is_valid(info.get('implementation_address')):
                Story.append(Paragraph(f"<b>Implementation:</b> {info.get('implementation_address')}", styles["Normal"]))
            if _is_valid(info.get('deployer')):
                Story.append(Paragraph(f"<b>Deployer:</b> {info.get('deployer')}", styles["Normal"]))
            if _is_valid(info.get('creation_tx')):
                Story.append(Paragraph(f"<b>Creation Tx:</b> {info.get('creation_tx')}", styles["Normal"]))
            if _is_valid(info.get('creation_block')):
                Story.append(Paragraph(f"<b>Creation Block:</b> {info.get('creation_block')}", styles["Normal"]))
            if _is_valid(info.get('optimization')):
                Story.append(Paragraph(f"<b>Optimization:</b> {info.get('optimization')}", styles["Normal"]))
            if _is_valid(goplus.get('owner_address')):
                Story.append(Paragraph(f"<b>Owner / Privileges:</b> {goplus.get('owner_address')}", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 4 - CODE INTELLIGENCE
            if slither:
                Story.append(Paragraph("<b>SECTION 4 - CODE INTELLIGENCE (STATIC ANALYSIS)</b>", styles["Heading2"]))
                for vuln in slither:
                    Story.append(Paragraph(f"- <b>{vuln.get('name', '')}</b> ({vuln.get('severity', '')}): {vuln.get('description', '')}", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # SECTION 5 - PROTOCOL INTELLIGENCE
            if goplus and _is_valid(goplus.get("overall")):
                Story.append(Paragraph("<b>SECTION 5 - PROTOCOL INTELLIGENCE (GOPLUS)</b>", styles["Heading2"]))
                Story.append(Paragraph(f"<b>Overall:</b> {goplus.get('overall')}", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # SECTION 6 - ECONOMIC ACTIVITY
            if _is_valid(raw.get("identity", {}).get("tx_count")):
                Story.append(Paragraph("<b>SECTION 6 - ECONOMIC ACTIVITY</b>", styles["Heading2"]))
                Story.append(Paragraph(f"<b>Transaction Count:</b> {raw.get('identity', {}).get('tx_count')}", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # SECTION 7 - HIGH-RISK INTERACTING WALLETS
            nodes = raw.get("graph_nodes", [])
            high_risk_nodes = [n for n in nodes if n.get("risk", 0) >= 70]
            if high_risk_nodes:
                Story.append(Paragraph("<b>SECTION 7 - HIGH-RISK INTERACTING WALLETS</b>", styles["Heading2"]))
                rows = []
                for n in high_risk_nodes[:10]:
                    rows.append([n.get("id", "")[:12]+"...", n.get("type", "Unknown"), str(n.get("risk", 0))])
                if rows:
                    Story.append(_build_table(["Wallet", "Type", "Risk"], rows, [140, 100, 60]))
                Story.append(Spacer(1, 12))

            # SECTION 8 - THREAT INTELLIGENCE
            if risk and risk.get("factors"):
                Story.append(Paragraph("<b>SECTION 8 - THREAT INTELLIGENCE</b>", styles["Heading2"]))
                for factor in risk.get("factors", []):
                    if isinstance(factor, str):
                        Story.append(Paragraph(f"- {translate(factor)}", styles["Normal"]))
                    else:
                        Story.append(Paragraph(f"- {translate(factor.get('reason'))} ", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # SECTION 9 - RISK SCORE BREAKDOWN
            Story.append(Paragraph("<b>SECTION 9 - RISK SCORE BREAKDOWN</b>", styles["Heading2"]))
            Story.append(Paragraph(f"<b>Overall Score:</b> {report.risk_score} / 100", styles["Normal"]))
            Story.append(Spacer(1, 12))

        elif report.entity_type == "bulk_batch":
            summary = raw.get("summary", {})
            results = raw.get("results", [])
            errors = raw.get("errors", [])
            sec = 1
            
            # SECTION 1 - MASTER EVIDENCE INTEGRITY
            Story.append(Paragraph(f"<b>SECTION {sec} - MASTER EVIDENCE INTEGRITY</b>", styles["Heading2"])); sec += 1
            Story.append(Paragraph(f"<b>SHA-256 Hash:</b> {report.report_hash}", styles["Normal"]))
            Story.append(Paragraph("<b>Signed:</b> Engine v2.0 | Node Source: Primary Intel Node", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 2 - CASE OVERVIEW
            Story.append(Paragraph(f"<b>SECTION {sec} - CASE OVERVIEW</b>", styles["Heading2"])); sec += 1
            total = sum(summary.values()) if summary else 0
            critical = summary.get("CRITICAL", 0)
            high = summary.get("HIGH", 0)
            Story.append(Paragraph(f"<b>Total Subjects Processed:</b> {total}", styles["Normal"]))
            Story.append(Paragraph(f"<b>Critical Risk Profiles:</b> {critical}", styles["Normal"]))
            Story.append(Paragraph(f"<b>High Risk Profiles:</b> {high}", styles["Normal"]))
            
            intel = raw.get("intelligence", {})
            priority_queue = intel.get("priority_queue", [])
            
            if critical > 0 or high > 0:
                reasons = []
                for p in priority_queue:
                    if p.get('reason') and p.get('score', 0) >= 60:
                        reasons.append(translate(p.get('reason').lower().replace('auto-detected: ', '')))
                        if len(reasons) >= 2: break
                reason_str = " and ".join(reasons) if reasons else "high-risk indicators"
                Story.append(Paragraph(f"<b>Assessment:</b> Batch risk is HIGH because {(critical + high)} entities exhibit {reason_str}, while the remaining subjects are low risk.", styles["Normal"]))
            else:
                Story.append(Paragraph(f"<b>Assessment:</b> Batch risk is LOW. No critical or high-risk entities detected in this batch.", styles["Normal"]))
            Story.append(Spacer(1, 12))

            # SECTION 3 - ENTITY REGISTRY
            if results:
                Story.append(Paragraph(f"<b>SECTION {sec} - ENTITY REGISTRY</b>", styles["Heading2"])); sec += 1
                rows = []
                for res in results[:20]:
                    addr = res.get("address", "")
                    addr_info = detect_address_type(addr)
                    rows.append([addr[:12]+"...", addr_info.get("coin", "Unknown"), res.get("label", ""), str(res.get("score", 0))])
                if rows:
                    Story.append(_build_table(["Address", "Network", "Risk Label", "Score"], rows, [100, 100, 60, 40]))
                Story.append(Spacer(1, 12))

            # SECTION 4 - PRIORITY INVESTIGATION QUEUE & TARGET PROFILING
            Story.append(Paragraph(f"<b>SECTION {sec} - TARGET PROFILING & INVESTIGATION QUEUE</b>", styles["Heading2"])); sec += 1
            
            top5 = intel.get("top5", {})
            if top5:
                # Add Most Connected
                mc = top5.get("most_connected", [])
                if mc and mc[0].get("value", 0) > 0:
                    Story.append(Paragraph("<b>Most Connected Nodes (Hubs):</b>", styles["Normal"]))
                    for item in mc[:3]:
                        if item.get("value", 0) > 0:
                            Story.append(Paragraph(f"- <b>{item.get('address')[:12]}...</b> ({item.get('value')} counterparties) - Risk: {item.get('risk_score')}", styles["Normal"]))
                    Story.append(Spacer(1, 6))
                
                # Add Highest Volume
                hv = top5.get("highest_volume", [])
                if hv and hv[0].get("value", 0) > 0:
                    Story.append(Paragraph("<b>Highest Volume Transactors:</b>", styles["Normal"]))
                    for item in hv[:3]:
                        if item.get("value", 0) > 0:
                            Story.append(Paragraph(f"- <b>{item.get('address')[:12]}...</b> ({item.get('value'):.2f} {item.get('nativeSymbol', 'ETH')}) - Risk: {item.get('risk_score')}", styles["Normal"]))
                    Story.append(Spacer(1, 6))

            priority_queue_filtered = [item for item in priority_queue if item.get("score", 0) >= 60]
            if priority_queue_filtered:
                Story.append(Paragraph("<b>Priority Investigation Targets (Risk >= 60):</b>", styles["Normal"]))
                rows = []
                for item in priority_queue_filtered[:15]:
                    rows.append([
                        item.get("address", "")[:12] + "...",
                        str(item.get("score", 0)),
                        item.get("reason", "")[:40]
                    ])
                if rows:
                    Story.append(_build_table(["Target Address", "Risk Score", "Primary Indicator"], rows, [100, 60, 200]))
            Story.append(Spacer(1, 12))

            # SECTION 5 - NETWORK CONNECTIONS / OVERLAP MATRIX
            similarity = intel.get("similarity_matrix", [])
            if similarity:
                Story.append(Paragraph(f"<b>SECTION {sec} - NETWORK CONNECTIONS / OVERLAP MATRIX</b>", styles["Heading2"])); sec += 1
                rows = []
                for sim in similarity[:15]:
                    rows.append([
                        sim.get("source", "")[:10] + "...",
                        sim.get("target", "")[:10] + "...",
                        f"{sim.get('score', 0):.2f}%",
                        sim.get("shared_counterparty", "")[:10] + "..."
                    ])
                if rows:
                    Story.append(_build_table(["Subject A", "Subject B", "Similarity", "Shared Node"], rows, [90, 90, 80, 90]))
                Story.append(Spacer(1, 12))

            # SECTION 6 - ACTIONABLE INTELLIGENCE
            if critical > 0 or high > 0:
                Story.append(Paragraph(f"<b>SECTION {sec} - ACTIONABLE INTELLIGENCE</b>", styles["Heading2"])); sec += 1
                high_addrs = [res.get("address", "") for res in results if res.get("score", 0) >= 60]
                if high_addrs:
                    Story.append(Paragraph(f"Immediate isolation and manual review strongly recommended for the following high-risk subjects:", styles["Normal"]))
                    for ha in high_addrs:
                        Story.append(Paragraph(f"- Priority Review: <b>{ha}</b>", styles["Normal"]))
                else:
                    Story.append(Paragraph(f"Immediate isolation and manual review strongly recommended for the {critical + high} high-risk subjects identified in the batch.", styles["Normal"]))
                Story.append(Spacer(1, 12))

            # SECTION 7 - INVESTIGATOR FINDINGS
            if errors:
                Story.append(Paragraph(f"<b>SECTION {sec} - INVESTIGATOR FINDINGS (ERRORS/OMISSIONS)</b>", styles["Heading2"])); sec += 1
                for err in errors:
                    Story.append(Paragraph(f"- <b>{err.get('address', '')[:12]}...</b>: {err.get('error', '')}", styles["Normal"]))
                Story.append(Spacer(1, 12))
                
            # SECTION 8 - THREAT INTELLIGENCE SUMMARY
            Story.append(Paragraph(f"<b>SECTION {sec} - THREAT INTELLIGENCE SUMMARY</b>", styles["Heading2"])); sec += 1
            Story.append(Paragraph(f"Batch processed with {len(errors)} failed queries.", styles["Normal"]))
            Story.append(Spacer(1, 12))

    doc.build(Story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    return buffer.getvalue()

def generate_case_pdf_report(case_id: int, db: Session) -> bytes:
    from database.models import Case, InvestigationLog
    case = db.query(Case).filter(Case.id == case_id).first()
    if not case:
        raise ValueError(f"Case {case_id} not found in database.")

    logs = db.query(InvestigationLog).filter(InvestigationLog.case_id == case_id).order_by(InvestigationLog.risk_score.desc()).all()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    Story = []

    # COVER BLOCK
    Story.append(Paragraph("<b>AXON - Verifiable Master Case Dossier</b>", styles["Title"]))
    Story.append(Spacer(1, 12))
    
    timestamp_str = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(case.created_at))
title_text = case.title if case.title and not case.title.startswith('[Placeholder') else f"Investigation Dossier - {case.id}"
    code_text = case.case_number if case.case_number and not case.case_number.startswith('[Placeholder') else f"AXON-C-{case.id}"
    Story.append(Paragraph(f"<b>Case ID:</b> {code_text}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Case Title:</b> {title_text}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Category:</b> {case.category or 'General'}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Priority:</b> {case.priority or 'P2'}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Timestamp:</b> {timestamp_str}", styles["Normal"]))
    Story.append(Spacer(1, 16))

    # SECTION 1 - CASE SUMMARY
    Story.append(Paragraph("<b>SECTION 1 - CASE SUMMARY</b>", styles["Heading2"]))
    if case.description and case.description.strip() and case.description.strip().lower() not in ["no summary available.", "no summary available", "n/a", "none"]:
        Story.append(Paragraph(case.description, styles["Normal"]))
    else:
        Story.append(Paragraph("Summary unavailable because no cross-entity relationships were identified.", styles["Normal"]))
    Story.append(Spacer(1, 8))
    
total = len(logs)
    critical = sum(1 for l in logs if l.risk_score >= 80)
    high = sum(1 for l in logs if 60 <= l.risk_score < 80)
    avg_risk = sum(l.risk_score for l in logs) // total if total > 0 else 0
    Story.append(Paragraph(f"<b>Total Entities Analyzed:</b> {total}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Critical Risk Profiles:</b> {critical}", styles["Normal"]))
    Story.append(Paragraph(f"<b>High Risk Profiles:</b> {high}", styles["Normal"]))
    Story.append(Paragraph(f"<b>Average Case Risk Score:</b> {avg_risk}/100", styles["Normal"]))
    Story.append(Spacer(1, 12))

    # SECTION 2 - ENTITY REGISTRY
    if logs:
        Story.append(Paragraph("<b>SECTION 2 - ENTITY REGISTRY</b>", styles["Heading2"]))
        rows = []
        for log in logs:
            label = "Unknown"
            if log.raw_data and isinstance(log.raw_data, dict):
                identity = log.raw_data.get("identity", {})
                if isinstance(identity, dict):
                    label = identity.get("label", "Unknown")
            rows.append([
                log.entity_address[:12] + "...",
                log.entity_type.upper(),
                label[:20],
                str(log.risk_score)
            ])
        if rows:
            Story.append(_build_table(["Address", "Type", "Label", "Risk Score"], rows, [100, 80, 140, 60]))
        Story.append(Spacer(1, 12))

    # SECTION 3 - CRITICAL VULNERABILITIES & KEY FINDINGS
    Story.append(Paragraph("<b>SECTION 3 - CRITICAL VULNERABILITIES & KEY FINDINGS</b>", styles["Heading2"]))
    findings = []
    import json
    for log in logs:
        signals = []
        try:
            if isinstance(log.triggered_signals, str):
                signals = json.loads(log.triggered_signals)
            elif isinstance(log.triggered_signals, list):
                signals = log.triggered_signals
        except: pass
        
        for sig in signals:
            reason = sig.get("reason", "") if isinstance(sig, dict) else str(sig)
            if reason:
                findings.append(f"{log.entity_address[:12]}... : {reason}")
    
    if findings:
        for f in findings[:10]:
            Story.append(Paragraph(f"- {f}", styles["Normal"]))
    else:
        Story.append(Paragraph("No critical signals triggered across case entities.", styles["Normal"]))
    Story.append(Spacer(1, 12))
    
    # SECTION 4 - CASE NOTES
    from database.models import CaseNote
    notes = db.query(CaseNote).filter(CaseNote.case_id == case_id).order_by(CaseNote.created_at.asc()).all()
    if notes:
        Story.append(Paragraph("<b>SECTION 4 - INVESTIGATOR NOTES</b>", styles["Heading2"]))
        for note in notes:
            note_time = time.strftime("%Y-%m-%d %H:%M", time.gmtime(note.created_at))
            Story.append(Paragraph(f"<b>[{note_time}]</b>: {note.content}", styles["Normal"]))
        Story.append(Spacer(1, 12))

    doc.build(Story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    return buffer.getvalue()
